site_name: Notas musicais
repo_url: https://github.com/PedroMargalha/NOTAS-MUSICAIS
repo_name: PedroMargalha/NOTAS-MUSICAIS
edit_uri: tree/main/docs

theme:
  name: material
  language: pt
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css