name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v4.1.1


      - name: Setup Python      
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Instalar o Poetry
        run: pip install poetry

      - name: Instalar dependências do projeto
        run: poetry install --without doc

      - name: Rodar os testes
        run: poetry run task test --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}