name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copia os arquivos
        uses: actions/checkout@v4.1.1


      - name: Setup Python      
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'

      - name: Instalar o Poetry
        run: pip install poetry

      - name: Instalar dependências do projeto
        run: poetry install --without doc

      - name: Rodar os testes
        run: poetry run task test --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: actions/checkout@master
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true # optional (default = false)
          files: ./coverage.xml # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true # optional (default = false)